# Generated by Django 4.2.7 on 2025-09-23 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nombre de Visualización')),
                ('parameter_type', models.CharField(choices=[('date', 'Fecha'), ('date_range', 'Rango de Fechas'), ('employee', 'Empleado'), ('department', 'Departamento'), ('metric', 'Métrica'), ('text', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('choice', 'Selección')], max_length=20, verbose_name='Tipo de Parámetro')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_required', models.BooleanField(default=False, verbose_name='Requerido')),
                ('default_value', models.TextField(blank=True, verbose_name='Valor por Defecto')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='Reglas de Validación')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='Opciones de Selección')),
            ],
            options={
                'verbose_name': 'Parámetro de Reporte',
                'verbose_name_plural': 'Parámetros de Reportes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('productivity', 'Productividad'), ('performance', 'Rendimiento'), ('attendance', 'Asistencia'), ('quality', 'Calidad'), ('safety', 'Seguridad'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Reporte')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Formato')),
                ('template_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración de Plantilla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual')], max_length=20, verbose_name='Frecuencia')),
                ('recipients', models.JSONField(default=list, verbose_name='Destinatarios')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parámetros')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='Última Generación')),
                ('next_generation', models.DateTimeField(verbose_name='Próxima Generación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reports.reporttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Reporte Programado',
                'verbose_name_plural': 'Reportes Programados',
                'ordering': ['-next_generation'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('status', models.CharField(choices=[('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='generating', max_length=20, verbose_name='Estado')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parámetros Utilizados')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del Archivo')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('generation_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo de Generación')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('scheduled_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.scheduledreport', verbose_name='Reporte Programado')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_gen_status_cacdbd_idx'), models.Index(fields=['template', 'created_at'], name='reports_gen_templat_b3931a_idx')],
            },
        ),
    ]
