# Generated by Django 4.2.7 on 2025-09-23 20:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('metric_type', models.CharField(choices=[('productivity', 'Productividad'), ('quality', 'Calidad'), ('efficiency', 'Eficiencia'), ('attendance', 'Asistencia'), ('safety', 'Seguridad')], max_length=20, verbose_name='Tipo de Métrica')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Objetivo')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Métrica de Rendimiento',
                'verbose_name_plural': 'Métricas de Rendimiento',
                'ordering': ['metric_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('evaluation_type', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual')], max_length=20, verbose_name='Tipo de Evaluación')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje General')),
                ('strengths', models.TextField(blank=True, verbose_name='Fortalezas')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='Áreas de Mejora')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='employees.employee', verbose_name='Empleado')),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por')),
            ],
            options={
                'verbose_name': 'Evaluación de Rendimiento',
                'verbose_name_plural': 'Evaluaciones de Rendimiento',
                'ordering': ['-end_date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'evaluation_type'], name='performance_employe_648a29_idx'), models.Index(fields=['start_date', 'end_date'], name='performance_start_d_f227ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Real')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='employees.employee', verbose_name='Empleado')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_performances', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_performances', to='performance.performancemetric', verbose_name='Métrica')),
            ],
            options={
                'verbose_name': 'Rendimiento de Empleado',
                'verbose_name_plural': 'Rendimientos de Empleados',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='performance_employe_723609_idx'), models.Index(fields=['metric', 'date'], name='performance_metric__bf062d_idx')],
                'unique_together': {('employee', 'date', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('total_break_time', models.DurationField(default=0, verbose_name='Tiempo Total de Descanso')),
                ('packages_processed', models.IntegerField(default=0, verbose_name='Paquetes Procesados')),
                ('trucks_received', models.IntegerField(default=0, verbose_name='Camiones Recibidos')),
                ('trucks_dispatched', models.IntegerField(default=0, verbose_name='Camiones Despachados')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Puntaje de Calidad')),
                ('safety_incidents', models.IntegerField(default=0, verbose_name='Incidentes de Seguridad')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_logs', to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro Diario de Trabajo',
                'verbose_name_plural': 'Registros Diarios de Trabajo',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='performance_employe_975de4_idx'), models.Index(fields=['date'], name='performance_date_e907b1_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
