# Generated by Django 4.2.7 on 2025-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.BooleanField(default=False, verbose_name='Es Plantilla'),
        ),
    ]
