# Generated by Django 4.2.7 on 2025-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_template_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
    ]
